
DATABASE_HOST=local
DATABASE_HOST=stage-skeleton.dooadex.com
DATABASE_HOST=prod-skeleton.dooadex.com



db:
  host: "localhost"
  port: 5432
  database: "dooadex_skeleton"
  synchronize: true

jwt:
  secret: "dooadexSecret"
